name: Terraform Deployment

on:
  push:
    branches:
      - main # Trigger the workflow on pushing to the 'main' branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository 
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0 # Specify the Terraform version you need

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Replace with your AWS region

      # Step 4: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 5: Validate Terraform files
        run: terraform validate

      # Step 6: Plan Terraform deployment
      - name: Plan Terraform deployment
        run: terraform plan

      # Step 7: Apply Terraform configuration
      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
name: Terraform Deployment

on:
  push:
    branches:
      - main # Trigger the workflow on pushing to the 'main' branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository 
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0 # Specify the Terraform version you need

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Replace with your AWS region

      # Step 4: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 5: Validate Terraform files
        run: terraform validate

      # Step 6: Plan Terraform deployment
      - name: Plan Terraform deployment
        run: terraform plan

      # Step 7: Apply Terraform configuration
      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
